import os
import glob
import re

dir_path = r'c:\NQT\local-rag-chatbot\backend'

replacements = {
    r'Học: ': 'Learn: ',
    r'Học:': 'Learn: ',
    r'Ngữ cảnh retrieve': 'Retrieve context',
    r'Upload PDF → Ingest vào ChromaDB → Chat kèm trích dẫn nguồn\.': 'Upload PDF -> Ingest to ChromaDB -> Chat with source citations.',
    r'Cấu hình đang dùng': 'Current configuration',
    r'Xóa lịch sử chat': 'Clear chat history',
    r'Tài liệu \(PDF\)': 'Documents (PDF)',
    r'Quản lý PDF': 'Manager PDF',
    r'Tạo database mới\. Tổng vectors:': 'Created new database. Total vectors:',
    r'Đã append dữ liệu\. Tổng vectors:': 'Appended data. Total vectors:',
    r'Mode không hợp lệ:': 'Invalid mode:',
    r'Không có documents/chunks để xử lý\. Kiểm tra thư mục data_dir và file PDF\.': 'No documents/chunks to process. Check data_dir directory and PDF files.',
    r'Đoạn (.*?) \- File: (.*?), Trang: (.*?)\n': r'Segment \1 - File: \2, Page: \3\n',
    r'Không tìm thấy thông tin liên quan\.': 'No relevant information found.',
    r'Windows: \.pdf và \.PDF trùng file → tránh đếm 2 lần': 'Windows: .pdf and .PDF are the same file -> avoid counting twice',
    r'Tự động restart khi sửa code \(cho môi trường dev\)': 'Auto restart on code change (for dev environment)',
    r'Lỗi: (.*)': r'Error: \1',
    r'Đã hủy bởi người dùng': 'Cancelled by user',
    r' HOÀN TẤT\! Vector Database đã sẵn sàng': ' COMPLETED! Vector Database is ready',
    r' Database đã lưu với (.*?) vectors': r' Database saved with \1 vectors',
    r'Hủy tạo database': 'Cancel database creation',
    r'Đã thêm vào database, tổng (.*?) vectors': r'Added to database, total \1 vectors',
    r'Sẽ thêm documents vào database hiện có': 'Will add documents to existing database',
    r'Đã xóa database cũ': 'Deleted old database',
    r'Ghi đè \(overwrite\)': 'Overwrite',
    r'Thêm vào \(append\)': 'Append',
    r'Hủy': 'Cancel',
    r'Database đã tồn tại:': 'Database already exists:',
    r'Lưu vào Vector Database\.\.\.': 'Save to Vector Database...',
    r'Tạo embeddings\.\.\.': 'Create embeddings...',
    r'Files:': 'Files:',
    r'Trung bình chunk:': 'Average chunk size:',
    r'Số chunks:': 'Number of chunks:',
    r'Số pages:': 'Number of pages:',
    r'Số files:': 'Number of files:',
    r'Thống kê:': 'Statistics:',
    r'Không có documents để xử lý': 'No documents to process',
    r'Xử lý PDF files\.\.\.': 'Process PDF files...',
    r'BẮT ĐẦU INGESTION': 'START INGESTION',
    r'Khởi động thất bại': 'Failed to start',
    r'Đã có lỗi xảy ra\.': 'An error occurred.',
    r'Lỗi không mong muốn:': 'Unexpected error:',
    r'Tạm biệt\!': 'Goodbye!',
    r'Không thể xử lý câu hỏi\. Vui lòng thử lại\.': 'Cannot process the question. Please try again.',
    r'Đã xóa lịch sử hội thoại': 'Deleted conversation history',
    r'Metrics đã được lưu': 'Metrics saved',
    r'Bạn:': 'You:',
    r'Kiểm tra:': 'Check:',
    r'Lỗi kết nối LLM:': 'LLM connection error:',
    r'LLM sẵn sàng': 'LLM ready',
    r'Đang kết nối': 'Connecting',
    r'Lỗi load database:': 'Database load error:',
    r'Database rỗng\!': 'Database is empty!',
    r'Database loaded:': 'Database loaded:',
    r'Đang load Vector Database\.\.\.': 'Loading Vector Database...',
    r'Database hợp lệ:': 'Valid database:',
    r'Chạy ingest_v4\.py trước để tạo database': 'Run ingestion script first to create database',
    r'Database không tồn tại:': 'Database does not exist:',
    r'Học: Object-oriented design for complex chatbot': 'Learn: Object element design for complex chatbot',
    r'Học: Singleton pattern for metrics': 'Learn: Singleton pattern for metrics',
    r'Học:  Measuring system performance': 'Learn: Measuring system performance',
    r'Nguồn tham khảo:': 'References:',
    r'Nguồn:': 'Source:',
    r'Lỗi khi retrieve with scores:': 'Error retrieving with scores:',
    r'Lỗi khi retrieve:': 'Error retrieving:',
    r'Không load được document nào': 'Failed to load any document',
    r'Không tìm thấy file PDF nào': 'No PDF files found',
    r'Lỗi khi split documents:': 'Error splitting documents:',
    r'Đã tạo (.*?) chunks': r'Created \1 chunks',
    r'Không tạo được chunks': 'Failed to create chunks',
    r'Đang chia nhỏ (.*?) documents\.\.\.': r'Splitting \1 documents...',
    r'tổng (.*?) trang': r'total \1 pages',
    r'(.*?) files thất bại,': r'\1 failed files,',
    r'Kết quả: (.*?) files thành công,': r'Result: \1 successful files,',
    r'Lỗi khi đọc': 'Error reading',
    r'Đã đọc (.*?) trang từ': r'Read \1 pages from',
    r'PDF rỗng:': 'Empty PDF:',
    r'Đang đọc:': 'Reading:',
    r'File hợp lệ:': 'Valid file:',
    r'File quá lớn:': 'File too large:',
    r'File không phải PDF:': 'File is not a PDF:',
    r'File không tồn tại:': 'File does not exist:',
    r'Tìm thấy (.*?) file PDF trong': r'Found \1 PDF files in',
    r'Directory không tồn tại:': 'Directory does not exist:',
    r'Đã xóa embedding cache': 'Cleared embedding cache',
    r'Lỗi khi tải embedding model:': 'Error loading embedding model:',
    r'Embedding model đã sẵn sàng': 'Embedding model ready',
    r'Đang tải embedding model:': 'Loading embedding model:',
    r'TRẢ LỜI \(giữ tính nhất quán với câu trả lời trước\):': 'ANSWER (keep consistency with previous answer):',
    r'CÂU HỎI TIẾP THEO:': 'NEXT QUESTION:',
    r'NGỮ CẢNH BỔ SUNG:': 'ADDITIONAL CONTEXT:',
    r'LỊCH SỬ:': 'HISTORY:',
    r'Dựa trên cuộc hội thoại trước đó và câu hỏi mới, hãy trả lời một cách nhất quán\.': 'Based on the previous conversation and new question, please answer consistently.',
    r'CÂU HỎI MỚI:': 'NEW QUESTION:',
    r'- Nếu suy luận thêm ngoài tài liệu, phải đánh dấu rõ là "suy luận"\.': '- If inferring beyond the document, must clearly mark as "inference".',
    r'- Mỗi kết luận/định nghĩa chính phải dẫn nguồn: tên file, chương/mục, trang\.': '- Every main conclusion/definition must cite source: filename, chapter/section, page.',
    r'- Trả lời như một gia sư, giải thích rõ ràng, từng bước\.': '- Answer like a tutor, explain clearly, step-by-step.',
    r'YÊU CẦU:': 'REQUIREMENT:',
    r'LỊCH SỬ HỘI THOẠI:': 'CONVERSATION HISTORY:',
    r'TRẢ LỜI:': 'ANSWER:',
    r'CÂU HỎI:': 'QUESTION:',
    r'NGỮ CẢNH TÀI LIỆU:': 'DOCUMENT CONTEXT:',
    r'QUY TẮC:': 'RULES:',
    r'Trợ lý': 'Assistant',
    r'Người dùng': 'User',
    r'Không có lịch sử hội thoại trước đó\.': 'No previous conversation history.',
    r'# Pydantic giúp validate config và có autocomplete': '# Pydantic helps validate config and provide autocomplete',
    r'# Học: Computed property': '# Learn: Computed property',
    r'\"\"\"Học: Computed property\"\"\"': '\"\"\"Learn: Computed property\"\"\"',
    r'\"\"\"Học: Cross-field validation\"\"\"': '\"\"\"Learn: Cross-field validation\"\"\"',
    r'Học:  Composition pattern': 'Learn: Composition pattern',
    r'# Học: Pydantic config': '# Learn: Pydantic config',
    r'Học: Recursive dictionary merging': 'Learn: Recursive dictionary merging',
    r'Học: Environment variables có priority cao nhất': 'Learn: Environment variables have the highest priority',
    r'Học:  Facade pattern - Simple interface': 'Learn: Facade pattern - Simple interface',
    r'# ---- Hàm Encode / Decode / Sanitize Security ----': '# ---- Encode / Decode / Sanitize Security ----',
    r'# Tạo Router để gộp chung nhóm API về Ghi chú': '# Create Router to group Notes API',
    r'# Xóa file': '# Delete file'
}

for root, dirs, files in os.walk(dir_path):
    if 'node_modules' in root or '.venv' in root or '__pycache__' in root:
        continue
    for file in files:
        if file.endswith('.py'):
            filepath = os.path.join(root, file)
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            
            original_content = content
            for vi, en in replacements.items():
                content = re.sub(vi, en, content)
            
            if content != original_content:
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f'Replaced in: {filepath}')
